import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Courses from '@/components/Landing/Courses'
import Hero from '@/components/Landing/Hero'
import Whyweb from '@/components/Landing/Whyweb'
import Footer from '@/components/Footer'
import IntroCards from '@/components/Landing/IntroCards'
import Pro from '@/components/Landing/Pro'



export default function Home() {

  return (

    <>
      <Head>
        <title>Hacked</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-full'>
        <div className=' bg-main-blue   '>
            <Header/>
            <Hero/>
        <div className=' bg-custom pb-52   '>
          <Whyweb/>
          <Pro/>  

          <Courses/>
        </div>
        <div className=' footer_hr'>  
          <Footer/>
        </div>
        </div>

      </main>
    </>
  )
}
